name: Setup toolchains for cross compilation and cross testing for Rust
description: GitHub Action for setup toolchains for cross compilation and cross testing for Rust

inputs:
  target:
    description: Target name
    required: true
  packages:
    description: Packages to install
    required: false
  runner:
    description: Test runner
    required: false
  qemu:
    description: QEMU version
    required: false
  wine:
    description: Wine version
    required: false

# Note:
# - inputs.* should be manually mapped to INPUT_* due to https://github.com/actions/runner/issues/665
# - Use GITHUB_*/RUNNER_* instead of github.*/runner.* due to https://github.com/actions/runner/issues/2185
runs:
  using: composite
  steps:
    - run: bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh"
      shell: bash
      env:
        INPUT_TARGET: ${{ inputs.target }}
        INPUT_PACKAGES: ${{ inputs.packages }}
        INPUT_RUNNER: ${{ inputs.runner }}
        INPUT_QEMU: ${{ inputs.qemu }}
        INPUT_WINE: ${{ inputs.wine }}
